const $ = selector => document.querySelector(selector);
const adminEmails = new Set(["sultan.figsolives@gmail.com", "figsandolives.kw@gmail.com"]);
const services = window.ORDERING_FIREBASE; let events=[];
const localDay=value=>new Date(value).toLocaleDateString("en-CA",{timeZone:"Asia/Kuwait"});
const today=localDay(Date.now()); $("#reportDate").value=today;
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const dateTime=value=>new Date(value).toLocaleString("ar-KW",{dateStyle:"medium",timeStyle:"short"});
function dayEvents(){return events.filter(event=>localDay(event.createdAt) === $("#reportDate").value);}
function grouped(list,key,label){const map=new Map();list.forEach(event=>{const name=event[key]||"غير محدد";map.set(name,(map.get(name)||0)+1)});return [...map].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([name,count],index)=>`<div class="rank-row"><i>${index+1}</i><span><b>${escapeHtml(name)}</b><small>${label}</small></span><strong>${count}</strong></div>`).join("")||'<div class="empty">لا توجد بيانات لهذا اليوم</div>'}
function metric(title,value,key,note){return `<button class="report-card" data-metric="${key}"><span>${title}</span><strong>${value}</strong><small>${note}</small></button>`}
function render(){const day=dayEvents(),visitors=new Map(),firstVisit=new Map();events.filter(event=>event.type==="visit").sort((a,b)=>Number(a.createdAt)-Number(b.createdAt)).forEach(event=>{if(!firstVisit.has(event.visitorId))firstVisit.set(event.visitorId,event);if(localDay(event.createdAt)===$("#reportDate").value)visitors.set(event.visitorId,event)});const visitList=[...visitors.values()];const newVisitors=visitList.filter(event=>firstVisit.get(event.visitorId)===event);const registered=visitList.filter(event=>event.customerName&&!newVisitors.includes(event));const newAccounts=day.filter(event=>event.type==="account_created");const carts=day.filter(event=>event.type==="cart_created");const completed=day.filter(event=>event.type==="checkout_complete");const abandoned=carts.filter(cart=>!completed.some(order=>order.visitorId===cart.visitorId));const anonymous=visitList.filter(event=>!event.customerName);$("#reportCards").innerHTML=[metric("زوار الموقع",visitList.length,"visit","اضغط لعرض التفاصيل"),metric("زوار جدد",newVisitors.length,"new","أول زيارة مسجلة"),metric("مسجلون مسبقاً",registered.length,"registered","زاروا الموقع بحساب سابق"),metric("حسابات أُنشئت اليوم",newAccounts.length,"account_created","تسجيل جديد"),metric("زوار لم يسجلوا الدخول",anonymous.length,"anonymous","بدون حساب"),metric("أنشأوا سلة",carts.length,"cart_created","أول منتج في السلة"),metric("أتموا الشراء",completed.length,"checkout_complete","دفع مؤكد"),metric("لم يتموا الشراء",abandoned.length,"abandoned","سلة بلا إتمام")].join("");$("#topProducts").innerHTML=grouped(day.filter(event=>event.type==="product_click"),"productName","نقرة");$("#topCategories").innerHTML=grouped(day.filter(event=>event.type==="category_click"),"categoryName","نقرة");}
function detail(key){const day=dayEvents();const visitors=[...new Map(day.filter(event=>event.type==="visit").map(event=>[event.visitorId,event])).values()];const firstVisit=new Map();events.filter(event=>event.type==="visit").sort((a,b)=>Number(a.createdAt)-Number(b.createdAt)).forEach(event=>{if(!firstVisit.has(event.visitorId))firstVisit.set(event.visitorId,event)});const completed=day.filter(event=>event.type==="checkout_complete"),carts=day.filter(event=>event.type==="cart_created");const lists={visit:visitors,new:visitors.filter(event=>firstVisit.get(event.visitorId)===event),registered:visitors.filter(event=>event.customerName&&firstVisit.get(event.visitorId)!==event),account_created:day.filter(event=>event.type==="account_created"),anonymous:visitors.filter(event=>!event.customerName),cart_created:carts,checkout_complete:completed,abandoned:carts.filter(cart=>!completed.some(order=>order.visitorId===cart.visitorId))};const labels={visit:"زوار الموقع",new:"الزوار الجدد",registered:"المسجلون مسبقاً",account_created:"الحسابات الجديدة",anonymous:"زوار بلا تسجيل دخول",cart_created:"من أنشأوا سلة",checkout_complete:"من أتموا الشراء",abandoned:"السلال غير المكتملة"};$("#detailTitle").textContent=labels[key];$("#detailList").innerHTML=lists[key].length?lists[key].map(event=>`<div class="detail-event"><div><b>${escapeHtml(event.customerName||"زائر غير مسجل")}</b><small>${escapeHtml(event.phone||"لا يوجد رقم هاتف")} · ${dateTime(event.createdAt)}</small></div><span>${escapeHtml(event.orderId||event.productName||event.categoryName||"زيارة")}</span></div>`).join(""):'<div class="empty">لا توجد تفاصيل لهذا اليوم</div>';$("#reportDetail").showModal();}
$("#reportDate").onchange=render;$("#reportCards").onclick=event=>{const card=event.target.closest("[data-metric]");if(card)detail(card.dataset.metric)};$("#closeReportDetail").onclick=()=>$("#reportDetail").close();
$("#adminGoogleLogin").onclick=async()=>{try{const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});await services.auth.signInWithPopup(provider)}catch(error){$("#adminAuthMessage").textContent=error.message||"تعذر تسجيل الدخول";}};
services.auth.onAuthStateChanged(user=>{const email=String(user?.email||"").toLowerCase();if(!user)return;if(!adminEmails.has(email)){ $("#adminAuthMessage").textContent="هذا الحساب غير مصرح له";services.auth.signOut();return;}$("#adminAuthGate").classList.add("hidden");services.database.ref("orderingPlatform/analyticsEvents").on("value",snapshot=>{events=Object.values(snapshot.val()||{});render();},()=>{$("#reportCards").innerHTML='<div class="empty">تعذر تحميل التقارير. تأكد من نشر قواعد Firebase الجديدة.</div>';});});
